name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Run gen.py
      run: python gen.py

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.2.0
      with:
        branch: gh-pages
        folder: _site
        token: ${{ secrets.GITHUB_TOKEN }}
